### ISSUE TITLE
Some Chinese characters don't display properly

### ISSUE THREAD

**Issue by sjtuross** [ich777/docker-krusader#1]
Could you add some additional Chinese fonts? Currently some Chinese characters don't display properly in Krusader.

I manually installed the following packages in container and set view font to "Noto Sans CJK SC" in Krusader, which solved the issue temporarily.

```
apt-get install --no-install-recommends ttf-wqy-zenhei fonts-wqy-microhei fonts-arphic-uming fonts-noto-cjk
```

Thank you.

**Comment by ich777** [comment]
@sjtuross sure thing, but I think these two are not needed: `ttf-wqy-zenhei fonts-wqy-microhei`.
I'll added it like in my [Firefox](https://github.com/ich777/docker-firefox/blob/master/Dockerfile#L8) container which is reported to work with Chinese characters, please report back if not.
I will close this for now, please reopen the issue if it doesn't work.
