### ISSUE TITLE
Can't launch Krusader on Android tablet anymore

### ISSUE THREAD

**Issue by Guesch** [ich777/docker-krusader#2]
Hey there,

Since the last update, I unfortunately cannot launch Krusader webUI on my Android tablet anymore (Samsug Galaxy Tab S7). I receive the following error message:

noVNC encountered an error:

Uncaught SyntaxError: The requested module '../core/util/browser.js' does not provide an export named 'isAndroid'
http://192.168.0.1:8089/app/ui.js:11:39
SyntaxError: The requested module '../core/util/browser.js' does not provide an export named 'isAndroid'

Cheers!

**Comment by ich777** [comment]
Please see my comment on the Unraid Forums over here: [Click](https://forums.unraid.net/topic/83786-support-ich777-application-dockers/?do=findComment&comment=1251183)

Please close the issue if that fixes your issue.

**Comment by Guesch** [comment]
Clearing cache did the trick indeed!
