### ISSUE TITLE
cannot access shares

### ISSUE THREAD

**Issue by neuronflow** [ich777/docker-krusader#4]
I cannot access my shares, when I click on them I get this:

<img width="1337" alt="Screenshot 2024-11-30 at 11 26 22" src="https://github.com/user-attachments/assets/fc4b7098-4518-4f0c-82ea-a20ab106cfb7">

**Comment by ich777** [comment]
Please send you `docker run` command and your Docker template.

Are you using exclusive shares?
How did you mount the shares, Read/Write Slave?

**Comment by neuronflow** [comment]
Thanks for looking into this. I believe this issue is not specific to your docker image, I have the same issue with the binhex one and cloud commander, I believe it might be a rights issue:

My shares:
<img width="1679" alt="Screenshot 2024-11-30 at 12 25 54" src="https://github.com/user-attachments/assets/96c11d20-9f57-4d16-aedf-d00a7f2f54c2">

unraid:
<img width="1724" alt="Screenshot 2024-11-30 at 12 26 51" src="https://github.com/user-attachments/assets/f11261b2-c0de-46cb-9470-e438f09c4ebb">

docker settings
<img width="1728" alt="Screenshot 2024-11-30 at 12 27 31" src="https://github.com/user-attachments/assets/0960523e-fd11-4ce2-9cc9-d495fb847685">

**Comment by neuronflow** [comment]
rw slave:
<img width="1202" alt="Screenshot 2024-11-30 at 12 28 58" src="https://github.com/user-attachments/assets/c482a1a0-5563-4544-a1bc-f347356b649d">

**Comment by ich777** [comment]
I think you are using exclusive shares, when using exclusive shares you have to change the path from `/mnt/user` to `/mnt` in the template and have to access the shares by using the real file path like `/mnt/cache/appdata` in the container.

**Comment by ich777** [comment]
…and please disable Privileged, this should be never be enabled in any Docker container since this is a huge security risk because you are giving permissions to the Docker container to controll the host and access everything on the host.

**Comment by neuronflow** [comment]
I just resetted your container to default. Privileged is on then. I agree with your assessment.

I also seem to use exclusive shares, true.

Setting the folder to `/mnt` seems to have solved it, thanks.

**Comment by ich777** [comment]
Please close the issue when it‘s solved.
Privileged should be off by default in my container.

**Comment by neuronflow** [comment]
Thanks for your help.
